site_name: Nav SDK开发指导手册
site_url: https://docs.navsdk.com/
extra_css:
  - css/font.css
copyright: Copyright &copy; 2024 navsdk.com
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.path
    - content.code.copy
    - toc.integrate
    - navigation.sections
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
plugins:
  - offline
  - search:
      lang:
          - en
          - ja
      separator: '[\s\-\.]+'
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: On this page
      toc_depth: 2
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
nav:
  - 首页: index.md
  - 编码规范: specification.md
